version: '3.8'

services:
  db:
    image: postgres:14-alpine # Use a specific version
    container_name: fastfood_db_fiap
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-fastfood_db} # Use environment variable from .env or default
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432" # Map host port from .env or default to container port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-fastfood_db}"]
        interval: 10s
        timeout: 5s
        retries: 5

  app:
    build: .
    container_name: fastfood_app_fiap
    restart: always
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "${PORT:-3000}:3000" # Map host port from .env or default to container port
    depends_on:
      db:
        condition: service_healthy # Wait for db to be healthy
    # Add volumes if needed for development (e.g., mapping src for hot-reloading)
    # volumes:
    #   - ./src:/app/src
    #   - ./logs:/app/logs # Map logs directory

volumes:
  postgres_data: # Define the named volume

